### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'ubuntu_data/dataset_1M.pkl'

### ISSUE THREAD

**Issue by SeekPoint** [SmartDataAnalytics/AK-DE-biGRU#1]
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU$ python -u run_models.py --h_dim 300 --mb_size 32 --n_epoch 20 --gpu --lr 0.0001
Traceback (most recent call last):
  File "run_models.py", line 47, in <module>
    max_seq_len=max_seq_len, gpu=args.gpu, use_fasttext=True)
  File "/home/ub16hp/ub16_prj/AK-DE-biGRU/data.py", line 29, in __init__
    with open(f'{path}/dataset_1M.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'ubuntu_data/dataset_1M.pkl'
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU$

**Comment by deepcode-debug** [comment]
Hi,

Please run the preprocess script which creates this file
````
pickle.dump(dataset, open('ubuntu_data/dataset_1M.pkl', 'wb'))
Re-run the script after this file is created. Let me know if there's a problem running this script

**Comment by SeekPoint** [comment]
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU/ubuntu_data$ 
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU/ubuntu_data$ ../../fastText/fasttext skipgram -input train.txt -dim 200 -output fast_text_200
Read 138M words
Number of words:  179659
Number of labels: 0
Progress: 100.0% words/sec/thread:   32123 lr:  0.000000 loss:  0.685871 ETA:   0h 0m
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU/ubuntu_data$ ll
total 4710384
drwxrwxr-x 2 ub16hp ub16hp       4096 11月 15 10:24 ./
drwxrwxr-x 6 ub16hp ub16hp       4096 11月 15 10:20 ../
-rw-rw-r-- 1 ub16hp ub16hp      78608 11月 14 15:17 command_description.npy
-rw-rw-r-- 1 ub16hp ub16hp 1198582267 11月 15 10:19 dataset_1M.pkl
-rw-rw-r-- 1 ub16hp ub16hp 1890783457 11月 15 10:55 fast_text_200.bin
-rw-rw-r-- 1 ub16hp ub16hp  314746963 11月 15 10:55 fast_text_200.vec
-rw-rw-r-- 1 ub16hp ub16hp        704 3月  18  2016 ReadMe.txt
-rw-rw-r-- 1 ub16hp ub16hp  354573855 3月  16  2016 test.txt
-rw-rw-r-- 1 ub16hp ub16hp  709142935 3月  16  2016 train.txt
-rw-rw-r-- 1 ub16hp ub16hp  353402955 3月  16  2016 valid.txt
-rw-rw-r-- 1 ub16hp ub16hp    2065742 3月  16  2016 vocab.txt
-rw-rw-r-- 1 ub16hp ub16hp        330 11月 14 20:53 yknote---fasttext---log
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU/ubuntu_data$ cd ..
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU$ python -u run_models.py --h_dim 300 --mb_size 32 --n_epoch 20 --gpu --lr 0.0001
Traceback (most recent call last):
  File "run_models.py", line 47, in <module>
    max_seq_len=max_seq_len, gpu=args.gpu, use_fasttext=True)
  File "/home/ub16hp/ub16_prj/AK-DE-biGRU/data.py", line 34, in __init__
    vectors = np.load(f'{path}/fast_text_200_v.npy')
  File "/home/ub16hp/ub16_prj/AK-DE-biGRU/.venv/lib/python3.6/site-packages/numpy/lib/npyio.py", line 372, in load
    fid = open(file, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'ubuntu_data/fast_text_200_v.npy'
(.venv) ub16hp@UB16HP:~/ub16_prj/AK-DE-biGRU$
