### ISSUE TITLE
Qeustion about domain knowledge?

### ISSUE THREAD

**Issue by chosenone75** [SmartDataAnalytics/AK-DE-biGRU#3]
could you  share the scripts for produce _ubuntu_description_.npy ?

**Comment by deepcode-debug** [comment]
Hi, we did by parsing the man page of the commands and then take only the description section. Then we used the vocabulary (word2index) to convert the words into their corresponding ids.
There were some manual efforts involved too for checking if the extraction was correct or not hence we didn't provide a script for it.
